name: VaultDemoForHotBlocks
version: 2.2
description: Give the player money with Vault as Demo for HotBlocks
author: Kirastur
website:  https://github.com/Kirastur/VaultDemoForHotBlocks


api-version: 1.19
load: POSTWORLD
main: de.polarwolf.hotvaultdemo.Main
depend: [HotBlocks, Vault]
